dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache: yarn

install:
  - yarn --silent

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - yarn lint
  - xvfb-run -a yarn test -- --no-progress --watch false --code-coverage --browsers ChromeNoSandbox
  - xvfb-run -a yarn e2e
  - yarn coverage
